//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMvc.Core.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMvc.Core.App_GlobalResources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاضافة.
        /// </summary>
        public static string AddDate {
            get {
                return ResourceManager.GetString("AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنوان.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فئة الدم.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المؤلف.
        /// </summary>
        public static string BookAuthor {
            get {
                return ResourceManager.GetString("BookAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الكتاب.
        /// </summary>
        public static string BookCode {
            get {
                return ResourceManager.GetString("BookCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر الكتاب.
        /// </summary>
        public static string BookPrice {
            get {
                return ResourceManager.GetString("BookPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الكتاب.
        /// </summary>
        public static string BookStatus {
            get {
                return ResourceManager.GetString("BookStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الكتاب.
        /// </summary>
        public static string BookTitle {
            get {
                return ResourceManager.GetString("BookTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة الإصدار.
        /// </summary>
        public static string BookYear {
            get {
                return ResourceManager.GetString("BookYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string CategoryType {
            get {
                return ResourceManager.GetString("CategoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكلية.
        /// </summary>
        public static string Collage {
            get {
                return ResourceManager.GetString("Collage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المحتوى.
        /// </summary>
        public static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز النموذج.
        /// </summary>
        public static string CtCode {
            get {
                return ResourceManager.GetString("CtCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string CtDescription {
            get {
                return ResourceManager.GetString("CtDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string CtTitle {
            get {
                return ResourceManager.GetString("CtTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفق1.
        /// </summary>
        public static string Document1 {
            get {
                return ResourceManager.GetString("Document1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفق2.
        /// </summary>
        public static string Document2 {
            get {
                return ResourceManager.GetString("Document2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفق3.
        /// </summary>
        public static string Document3 {
            get {
                return ResourceManager.GetString("Document3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ اصدار الوثيقة.
        /// </summary>
        public static string DocumentDate {
            get {
                return ResourceManager.GetString("DocumentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوثيقة.
        /// </summary>
        public static string DocumentNo {
            get {
                return ResourceManager.GetString("DocumentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكنية.
        /// </summary>
        public static string FamilyName {
            get {
                return ResourceManager.GetString("FamilyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرمز.
        /// </summary>
        public static string FMenuCode {
            get {
                return ResourceManager.GetString("FMenuCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string FMenuDescription {
            get {
                return ResourceManager.GetString("FMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السعر.
        /// </summary>
        public static string FMenuPrice {
            get {
                return ResourceManager.GetString("FMenuPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم  نوع الطعام.
        /// </summary>
        public static string FMenuTitle {
            get {
                return ResourceManager.GetString("FMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ اصدار الحفيظة.
        /// </summary>
        public static string HafizaDate {
            get {
                return ResourceManager.GetString("HafizaDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحفيظة.
        /// </summary>
        public static string HafizaNo {
            get {
                return ResourceManager.GetString("HafizaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لاحقة الصورة.
        /// </summary>
        public static string ImageExtension {
            get {
                return ResourceManager.GetString("ImageExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول الصورة.
        /// </summary>
        public static string ImageLength {
            get {
                return ResourceManager.GetString("ImageLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصورة.
        /// </summary>
        public static string ImagePath {
            get {
                return ResourceManager.GetString("ImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صيغة البريد الالكتروني خاطئة.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء الإقامة.
        /// </summary>
        public static string IqamaEndDate {
            get {
                return ResourceManager.GetString("IqamaEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإقامة.
        /// </summary>
        public static string IqamaNo {
            get {
                return ResourceManager.GetString("IqamaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان اصدار الإقامة.
        /// </summary>
        public static string IqamaPlace {
            get {
                return ResourceManager.GetString("IqamaPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ اصدار الإقامة.
        /// </summary>
        public static string IqamaStartDate {
            get {
                return ResourceManager.GetString("IqamaStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال؟.
        /// </summary>
        public static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        public static string ModifyDate {
            get {
                return ResourceManager.GetString("ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوطني.
        /// </summary>
        public static string NationalNo {
            get {
                return ResourceManager.GetString("NationalNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out.
        /// </summary>
        public static string Out {
            get {
                return ResourceManager.GetString("Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المالك.
        /// </summary>
        public static string OwnerCode {
            get {
                return ResourceManager.GetString("OwnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء الجواز.
        /// </summary>
        public static string PassportEndDate {
            get {
                return ResourceManager.GetString("PassportEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم جواز السفر.
        /// </summary>
        public static string PassportNo {
            get {
                return ResourceManager.GetString("PassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان اصدار الجواز.
        /// </summary>
        public static string PassportPlace {
            get {
                return ResourceManager.GetString("PassportPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الولادة.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء الاختيار.
        /// </summary>
        public static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأولوية.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكمية.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حقل  {0} هو حقل مطلوب.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الثاني.
        /// </summary>
        public static string SecondName {
            get {
                return ResourceManager.GetString("SecondName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب أن لا يزيد طول حقل {0} عن {1} محرف.
        /// </summary>
        public static string StringLengthError {
            get {
                return ResourceManager.GetString("StringLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود القالب.
        /// </summary>
        public static string TempCode {
            get {
                return ResourceManager.GetString("TempCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوصف.
        /// </summary>
        public static string TempDescription {
            get {
                return ResourceManager.GetString("TempDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القالب افتراضي؟.
        /// </summary>
        public static string TempIsDefualt {
            get {
                return ResourceManager.GetString("TempIsDefualt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القالب.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسار القالب.
        /// </summary>
        public static string TempPath {
            get {
                return ResourceManager.GetString("TempPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم القالب.
        /// </summary>
        public static string TempTitle {
            get {
                return ResourceManager.GetString("TempTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز النافذة.
        /// </summary>
        public static string TermCode {
            get {
                return ResourceManager.GetString("TermCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف النافذة.
        /// </summary>
        public static string TermDescription {
            get {
                return ResourceManager.GetString("TermDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم النافذة.
        /// </summary>
        public static string TermTitle {
            get {
                return ResourceManager.GetString("TermTitle", resourceCulture);
            }
        }
    }
}
